title: Renzie Aditya Fattah Hudiantoro # your name (or website title) here
logo: "images/Renzie - PJ - Akademik New 2.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, My Name is Renzie Aditya, an undergraduate student at the Faculty of Mathematics and Natural Sciences, Universitas Indonesia.
  <br><br>
  I am currently a Data Science Assistant at the Mathematics Department. I Specialize in Deep Learning, Bioinformatics, and Biomedical Image Processing
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
